server:
  port: 9915

# API Registry client configuration
# Netflix Eureka Client configuration
eureka:
  instance:
    appname: ${spring.application.name}
    healthCheckUrlPath: /production-support/health
    statusPageUrlPath: /production-support/info
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    nonSecurePort: ${server.port}
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8080}/registry/eureka/

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      type: signed
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

# Spring health monitoring
management:
  health:
    jms:
      enabled: false

#
# Logging configuration
#
# Logging
logging:
  level:
    web: TRACE
    com.backbase: INFO
    org.springframework: INFO